export const SET_SHEET_DATA = "SET_SHEET_DATA";
export const SET_SEARCH_CRITERIA = "SET_SEARCH_CRITERIA ";
export const SET_TABLE_DATA = "SET_TABLE_DATA";

export const columnNames = {
  ID: "Id",
  CUSTOMER_NAME: "Customer Name",
  INVOICE: "Invoice",
  INVOICE_DATE: "Invoice Date",
  TMS_FILE_NO: "TMS File No",
  ORDER_VALUE: "Order Value",
  ORDER_RATE: "Order Rate",
  COMMISSION_OWNED: "Commission Owned",
};

export const inputLabelNames = {
  TMS_FILE_NO: "TMS File Number",
  CUSTOMER_NAME: "Customer Name",
  COUNTRY: "Country",
  CURRENCY_TYPE: "Currency Type",
  ORDER_VALUE: "Order Value",
  COMMISSION_RATE: "Commission Rate",
  COMMISSION_Value: "Commission Value",
};

export const countryList = [
  { code: "", code3: "", name: "", number: "" },
  { code: "AF", code3: "AFG", name: "Afghanistan", number: "004" },
  { code: "AL", code3: "ALB", name: "Albania", number: "008" },
  { code: "DZ", code3: "DZA", name: "Algeria", number: "012" },
  { code: "AS", code3: "ASM", name: "American Samoa", number: "016" },
  { code: "AD", code3: "AND", name: "Andorra", number: "020" },
  { code: "AO", code3: "AGO", name: "Angola", number: "024" },
  { code: "AI", code3: "AIA", name: "Anguilla", number: "660" },
  { code: "AQ", code3: "ATA", name: "Antarctica", number: "010" },
  { code: "AG", code3: "ATG", name: "Antigua and Barbuda", number: "028" },
  { code: "AR", code3: "ARG", name: "Argentina", number: "032" },
  { code: "AM", code3: "ARM", name: "Armenia", number: "051" },
  { code: "AW", code3: "ABW", name: "Aruba", number: "533" },
  { code: "AU", code3: "AUS", name: "Australia", number: "036" },
  { code: "AT", code3: "AUT", name: "Austria", number: "040" },
  { code: "AZ", code3: "AZE", name: "Azerbaijan", number: "031" },
  { code: "BS", code3: "BHS", name: "Bahamas (the)", number: "044" },
  { code: "BH", code3: "BHR", name: "Bahrain", number: "048" },
  { code: "BD", code3: "BGD", name: "Bangladesh", number: "050" },
  { code: "BB", code3: "BRB", name: "Barbados", number: "052" },
  { code: "BY", code3: "BLR", name: "Belarus", number: "112" },
  { code: "BE", code3: "BEL", name: "Belgium", number: "056" },
  { code: "BZ", code3: "BLZ", name: "Belize", number: "084" },
  { code: "BJ", code3: "BEN", name: "Benin", number: "204" },
  { code: "BM", code3: "BMU", name: "Bermuda", number: "060" },
  { code: "BT", code3: "BTN", name: "Bhutan", number: "064" },
  {
    code: "BO",
    code3: "BOL",
    name: "Bolivia (Plurinational State of)",
    number: "068",
  },
  {
    code: "BQ",
    code3: "BES",
    name: "Bonaire, Sint Eustatius and Saba",
    number: "535",
  },
  { code: "BA", code3: "BIH", name: "Bosnia and Herzegovina", number: "070" },
  { code: "BW", code3: "BWA", name: "Botswana", number: "072" },
  { code: "BV", code3: "BVT", name: "Bouvet Island", number: "074" },
  { code: "BR", code3: "BRA", name: "Brazil", number: "076" },
  {
    code: "IO",
    code3: "IOT",
    name: "British Indian Ocean Territory (the)",
    number: "086",
  },
  { code: "BN", code3: "BRN", name: "Brunei Darussalam", number: "096" },
  { code: "BG", code3: "BGR", name: "Bulgaria", number: "100" },
  { code: "BF", code3: "BFA", name: "Burkina Faso", number: "854" },
  { code: "BI", code3: "BDI", name: "Burundi", number: "108" },
  { code: "CV", code3: "CPV", name: "Cabo Verde", number: "132" },
  { code: "KH", code3: "KHM", name: "Cambodia", number: "116" },
  { code: "CM", code3: "CMR", name: "Cameroon", number: "120" },
  { code: "CA", code3: "CAN", name: "Canada", number: "124" },
  { code: "KY", code3: "CYM", name: "Cayman Islands (the)", number: "136" },
  {
    code: "CF",
    code3: "CAF",
    name: "Central African Republic (the)",
    number: "140",
  },
  { code: "TD", code3: "TCD", name: "Chad", number: "148" },
  { code: "CL", code3: "CHL", name: "Chile", number: "152" },
  { code: "CN", code3: "CHN", name: "China", number: "156" },
  { code: "CX", code3: "CXR", name: "Christmas Island", number: "162" },
  {
    code: "CC",
    code3: "CCK",
    name: "Cocos (Keeling) Islands (the)",
    number: "166",
  },
  { code: "CO", code3: "COL", name: "Colombia", number: "170" },
  { code: "KM", code3: "COM", name: "Comoros (the)", number: "174" },
  {
    code: "CD",
    code3: "COD",
    name: "Congo (the Democratic Republic of the)",
    number: "180",
  },
  { code: "CG", code3: "COG", name: "Congo (the)", number: "178" },
  { code: "CK", code3: "COK", name: "Cook Islands (the)", number: "184" },
  { code: "CR", code3: "CRI", name: "Costa Rica", number: "188" },
  { code: "HR", code3: "HRV", name: "Croatia", number: "191" },
  { code: "CU", code3: "CUB", name: "Cuba", number: "192" },
  { code: "CW", code3: "CUW", name: "Curaçao", number: "531" },
  { code: "CY", code3: "CYP", name: "Cyprus", number: "196" },
  { code: "CZ", code3: "CZE", name: "Czechia", number: "203" },
  { code: "CI", code3: "CIV", name: "Côte d'Ivoire", number: "384" },
  { code: "DK", code3: "DNK", name: "Denmark", number: "208" },
  { code: "DJ", code3: "DJI", name: "Djibouti", number: "262" },
  { code: "DM", code3: "DMA", name: "Dominica", number: "212" },
  { code: "DO", code3: "DOM", name: "Dominican Republic (the)", number: "214" },
  { code: "EC", code3: "ECU", name: "Ecuador", number: "218" },
  { code: "EG", code3: "EGY", name: "Egypt", number: "818" },
  { code: "SV", code3: "SLV", name: "El Salvador", number: "222" },
  { code: "GQ", code3: "GNQ", name: "Equatorial Guinea", number: "226" },
  { code: "ER", code3: "ERI", name: "Eritrea", number: "232" },
  { code: "EE", code3: "EST", name: "Estonia", number: "233" },
  { code: "SZ", code3: "SWZ", name: "Eswatini", number: "748" },
  { code: "ET", code3: "ETH", name: "Ethiopia", number: "231" },
  {
    code: "FK",
    code3: "FLK",
    name: "Falkland Islands (the) [Malvinas]",
    number: "238",
  },
  { code: "FO", code3: "FRO", name: "Faroe Islands (the)", number: "234" },
  { code: "FJ", code3: "FJI", name: "Fiji", number: "242" },
  { code: "FI", code3: "FIN", name: "Finland", number: "246" },
  { code: "FR", code3: "FRA", name: "France", number: "250" },
  { code: "GF", code3: "GUF", name: "French Guiana", number: "254" },
  { code: "PF", code3: "PYF", name: "French Polynesia", number: "258" },
  {
    code: "TF",
    code3: "ATF",
    name: "French Southern Territories (the)",
    number: "260",
  },
  { code: "GA", code3: "GAB", name: "Gabon", number: "266" },
  { code: "GM", code3: "GMB", name: "Gambia (the)", number: "270" },
  { code: "GE", code3: "GEO", name: "Georgia", number: "268" },
  { code: "DE", code3: "DEU", name: "Germany", number: "276" },
  { code: "GH", code3: "GHA", name: "Ghana", number: "288" },
  { code: "GI", code3: "GIB", name: "Gibraltar", number: "292" },
  { code: "GR", code3: "GRC", name: "Greece", number: "300" },
  { code: "GL", code3: "GRL", name: "Greenland", number: "304" },
  { code: "GD", code3: "GRD", name: "Grenada", number: "308" },
  { code: "GP", code3: "GLP", name: "Guadeloupe", number: "312" },
  { code: "GU", code3: "GUM", name: "Guam", number: "316" },
  { code: "GT", code3: "GTM", name: "Guatemala", number: "320" },
  { code: "GG", code3: "GGY", name: "Guernsey", number: "831" },
  { code: "GN", code3: "GIN", name: "Guinea", number: "324" },
  { code: "GW", code3: "GNB", name: "Guinea-Bissau", number: "624" },
  { code: "GY", code3: "GUY", name: "Guyana", number: "328" },
  { code: "HT", code3: "HTI", name: "Haiti", number: "332" },
  {
    code: "HM",
    code3: "HMD",
    name: "Heard Island and McDonald Islands",
    number: "334",
  },
  { code: "VA", code3: "VAT", name: "Holy See (the)", number: "336" },
  { code: "HN", code3: "HND", name: "Honduras", number: "340" },
  { code: "HK", code3: "HKG", name: "Hong Kong", number: "344" },
  { code: "HU", code3: "HUN", name: "Hungary", number: "348" },
  { code: "IS", code3: "ISL", name: "Iceland", number: "352" },
  { code: "IN", code3: "IND", name: "India", number: "356" },
  { code: "ID", code3: "IDN", name: "Indonesia", number: "360" },
  {
    code: "IR",
    code3: "IRN",
    name: "Iran (Islamic Republic of)",
    number: "364",
  },
  { code: "IQ", code3: "IRQ", name: "Iraq", number: "368" },
  { code: "IE", code3: "IRL", name: "Ireland", number: "372" },
  { code: "IM", code3: "IMN", name: "Isle of Man", number: "833" },
  { code: "IL", code3: "ISR", name: "Israel", number: "376" },
  { code: "IT", code3: "ITA", name: "Italy", number: "380" },
  { code: "JM", code3: "JAM", name: "Jamaica", number: "388" },
  { code: "JP", code3: "JPN", name: "Japan", number: "392" },
  { code: "JE", code3: "JEY", name: "Jersey", number: "832" },
  { code: "JO", code3: "JOR", name: "Jordan", number: "400" },
  { code: "KZ", code3: "KAZ", name: "Kazakhstan", number: "398" },
  { code: "KE", code3: "KEN", name: "Kenya", number: "404" },
  { code: "KI", code3: "KIR", name: "Kiribati", number: "296" },
  {
    code: "KP",
    code3: "PRK",
    name: "Korea (the Democratic People's Republic of)",
    number: "408",
  },
  { code: "KR", code3: "KOR", name: "Korea (the Republic of)", number: "410" },
  { code: "KW", code3: "KWT", name: "Kuwait", number: "414" },
  { code: "KG", code3: "KGZ", name: "Kyrgyzstan", number: "417" },
  {
    code: "LA",
    code3: "LAO",
    name: "Lao People's Democratic Republic (the)",
    number: "418",
  },
  { code: "LV", code3: "LVA", name: "Latvia", number: "428" },
  { code: "LB", code3: "LBN", name: "Lebanon", number: "422" },
  { code: "LS", code3: "LSO", name: "Lesotho", number: "426" },
  { code: "LR", code3: "LBR", name: "Liberia", number: "430" },
  { code: "LY", code3: "LBY", name: "Libya", number: "434" },
  { code: "LI", code3: "LIE", name: "Liechtenstein", number: "438" },
  { code: "LT", code3: "LTU", name: "Lithuania", number: "440" },
  { code: "LU", code3: "LUX", name: "Luxembourg", number: "442" },
  { code: "MO", code3: "MAC", name: "Macao", number: "446" },
  { code: "MG", code3: "MDG", name: "Madagascar", number: "450" },
  { code: "MW", code3: "MWI", name: "Malawi", number: "454" },
  { code: "MY", code3: "MYS", name: "Malaysia", number: "458" },
  { code: "MV", code3: "MDV", name: "Maldives", number: "462" },
  { code: "ML", code3: "MLI", name: "Mali", number: "466" },
  { code: "MT", code3: "MLT", name: "Malta", number: "470" },
  { code: "MH", code3: "MHL", name: "Marshall Islands (the)", number: "584" },
  { code: "MQ", code3: "MTQ", name: "Martinique", number: "474" },
  { code: "MR", code3: "MRT", name: "Mauritania", number: "478" },
  { code: "MU", code3: "MUS", name: "Mauritius", number: "480" },
  { code: "YT", code3: "MYT", name: "Mayotte", number: "175" },
  { code: "MX", code3: "MEX", name: "Mexico", number: "484" },
  {
    code: "FM",
    code3: "FSM",
    name: "Micronesia (Federated States of)",
    number: "583",
  },
  {
    code: "MD",
    code3: "MDA",
    name: "Moldova (the Republic of)",
    number: "498",
  },
  { code: "MC", code3: "MCO", name: "Monaco", number: "492" },
  { code: "MN", code3: "MNG", name: "Mongolia", number: "496" },
  { code: "ME", code3: "MNE", name: "Montenegro", number: "499" },
  { code: "MS", code3: "MSR", name: "Montserrat", number: "500" },
  { code: "MA", code3: "MAR", name: "Morocco", number: "504" },
  { code: "MZ", code3: "MOZ", name: "Mozambique", number: "508" },
  { code: "MM", code3: "MMR", name: "Myanmar", number: "104" },
  { code: "NA", code3: "NAM", name: "Namibia", number: "516" },
  { code: "NR", code3: "NRU", name: "Nauru", number: "520" },
  { code: "NP", code3: "NPL", name: "Nepal", number: "524" },
  { code: "NL", code3: "NLD", name: "Netherlands (the)", number: "528" },
  { code: "NC", code3: "NCL", name: "New Caledonia", number: "540" },
  { code: "NZ", code3: "NZL", name: "New Zealand", number: "554" },
  { code: "NI", code3: "NIC", name: "Nicaragua", number: "558" },
  { code: "NE", code3: "NER", name: "Niger (the)", number: "562" },
  { code: "NG", code3: "NGA", name: "Nigeria", number: "566" },
  { code: "NU", code3: "NIU", name: "Niue", number: "570" },
  { code: "NF", code3: "NFK", name: "Norfolk Island", number: "574" },
  {
    code: "MP",
    code3: "MNP",
    name: "Northern Mariana Islands (the)",
    number: "580",
  },
  { code: "NO", code3: "NOR", name: "Norway", number: "578" },
  { code: "OM", code3: "OMN", name: "Oman", number: "512" },
  { code: "PK", code3: "PAK", name: "Pakistan", number: "586" },
  { code: "PW", code3: "PLW", name: "Palau", number: "585" },
  { code: "PS", code3: "PSE", name: "Palestine, State of", number: "275" },
  { code: "PA", code3: "PAN", name: "Panama", number: "591" },
  { code: "PG", code3: "PNG", name: "Papua New Guinea", number: "598" },
  { code: "PY", code3: "PRY", name: "Paraguay", number: "600" },
  { code: "PE", code3: "PER", name: "Peru", number: "604" },
  { code: "PH", code3: "PHL", name: "Philippines (the)", number: "608" },
  { code: "PN", code3: "PCN", name: "Pitcairn", number: "612" },
  { code: "PL", code3: "POL", name: "Poland", number: "616" },
  { code: "PT", code3: "PRT", name: "Portugal", number: "620" },
  { code: "PR", code3: "PRI", name: "Puerto Rico", number: "630" },
  { code: "QA", code3: "QAT", name: "Qatar", number: "634" },
  {
    code: "MK",
    code3: "MKD",
    name: "Republic of North Macedonia",
    number: "807",
  },
  { code: "RO", code3: "ROU", name: "Romania", number: "642" },
  { code: "RU", code3: "RUS", name: "Russian Federation (the)", number: "643" },
  { code: "RW", code3: "RWA", name: "Rwanda", number: "646" },
  { code: "RE", code3: "REU", name: "Réunion", number: "638" },
  { code: "BL", code3: "BLM", name: "Saint Barthélemy", number: "652" },
  {
    code: "SH",
    code3: "SHN",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    number: "654",
  },
  { code: "KN", code3: "KNA", name: "Saint Kitts and Nevis", number: "659" },
  { code: "LC", code3: "LCA", name: "Saint Lucia", number: "662" },
  {
    code: "MF",
    code3: "MAF",
    name: "Saint Martin (French part)",
    number: "663",
  },
  {
    code: "PM",
    code3: "SPM",
    name: "Saint Pierre and Miquelon",
    number: "666",
  },
  {
    code: "VC",
    code3: "VCT",
    name: "Saint Vincent and the Grenadines",
    number: "670",
  },
  { code: "WS", code3: "WSM", name: "Samoa", number: "882" },
  { code: "SM", code3: "SMR", name: "San Marino", number: "674" },
  { code: "ST", code3: "STP", name: "Sao Tome and Principe", number: "678" },
  { code: "SA", code3: "SAU", name: "Saudi Arabia", number: "682" },
  { code: "SN", code3: "SEN", name: "Senegal", number: "686" },
  { code: "RS", code3: "SRB", name: "Serbia", number: "688" },
  { code: "SC", code3: "SYC", name: "Seychelles", number: "690" },
  { code: "SL", code3: "SLE", name: "Sierra Leone", number: "694" },
  { code: "SG", code3: "SGP", name: "Singapore", number: "702" },
  {
    code: "SX",
    code3: "SXM",
    name: "Sint Maarten (Dutch part)",
    number: "534",
  },
  { code: "SK", code3: "SVK", name: "Slovakia", number: "703" },
  { code: "SI", code3: "SVN", name: "Slovenia", number: "705" },
  { code: "SB", code3: "SLB", name: "Solomon Islands", number: "090" },
  { code: "SO", code3: "SOM", name: "Somalia", number: "706" },
  { code: "ZA", code3: "ZAF", name: "South Africa", number: "710" },
  {
    code: "GS",
    code3: "SGS",
    name: "South Georgia and the South Sandwich Islands",
    number: "239",
  },
  { code: "SS", code3: "SSD", name: "South Sudan", number: "728" },
  { code: "ES", code3: "ESP", name: "Spain", number: "724" },
  { code: "LK", code3: "LKA", name: "Sri Lanka", number: "144" },
  { code: "SD", code3: "SDN", name: "Sudan (the)", number: "729" },
  { code: "SR", code3: "SUR", name: "Suriname", number: "740" },
  { code: "SJ", code3: "SJM", name: "Svalbard and Jan Mayen", number: "744" },
  { code: "SE", code3: "SWE", name: "Sweden", number: "752" },
  { code: "CH", code3: "CHE", name: "Switzerland", number: "756" },
  { code: "SY", code3: "SYR", name: "Syrian Arab Republic", number: "760" },
  { code: "TW", code3: "TWN", name: "Taiwan", number: "158" },
  { code: "TJ", code3: "TJK", name: "Tajikistan", number: "762" },
  {
    code: "TZ",
    code3: "TZA",
    name: "Tanzania, United Republic of",
    number: "834",
  },
  { code: "TH", code3: "THA", name: "Thailand", number: "764" },
  { code: "TL", code3: "TLS", name: "Timor-Leste", number: "626" },
  { code: "TG", code3: "TGO", name: "Togo", number: "768" },
  { code: "TK", code3: "TKL", name: "Tokelau", number: "772" },
  { code: "TO", code3: "TON", name: "Tonga", number: "776" },
  { code: "TT", code3: "TTO", name: "Trinidad and Tobago", number: "780" },
  { code: "TN", code3: "TUN", name: "Tunisia", number: "788" },
  { code: "TR", code3: "TUR", name: "Turkey", number: "792" },
  { code: "TM", code3: "TKM", name: "Turkmenistan", number: "795" },
  {
    code: "TC",
    code3: "TCA",
    name: "Turks and Caicos Islands (the)",
    number: "796",
  },
  { code: "TV", code3: "TUV", name: "Tuvalu", number: "798" },
  { code: "UG", code3: "UGA", name: "Uganda", number: "800" },
  { code: "UA", code3: "UKR", name: "Ukraine", number: "804" },
  {
    code: "AE",
    code3: "ARE",
    name: "United Arab Emirates (the)",
    number: "784",
  },
  {
    code: "GB",
    code3: "GBR",
    name: "United Kingdom of Great Britain and Northern Ireland (the)",
    number: "826",
  },
  {
    code: "UM",
    code3: "UMI",
    name: "United States Minor Outlying Islands (the)",
    number: "581",
  },
  {
    code: "US",
    code3: "USA",
    name: "United States of America (the)",
    number: "840",
  },
  { code: "UY", code3: "URY", name: "Uruguay", number: "858" },
  { code: "UZ", code3: "UZB", name: "Uzbekistan", number: "860" },
  { code: "VU", code3: "VUT", name: "Vanuatu", number: "548" },
  {
    code: "VE",
    code3: "VEN",
    name: "Venezuela (Bolivarian Republic of)",
    number: "862",
  },
  { code: "VN", code3: "VNM", name: "Viet Nam", number: "704" },
  { code: "VG", code3: "VGB", name: "Virgin Islands (British)", number: "092" },
  { code: "VI", code3: "VIR", name: "Virgin Islands (U.S.)", number: "850" },
  { code: "WF", code3: "WLF", name: "Wallis and Futuna", number: "876" },
  { code: "EH", code3: "ESH", name: "Western Sahara", number: "732" },
  { code: "YE", code3: "YEM", name: "Yemen", number: "887" },
  { code: "ZM", code3: "ZMB", name: "Zambia", number: "894" },
  { code: "ZW", code3: "ZWE", name: "Zimbabwe", number: "716" },
  { code: "AX", code3: "ALA", name: "Åland Islands", number: "248" },
];

export const currencyList = [
  { name: "", currencyCode: "", currencyName: "" },
  {
    name: "AFGHANISTAN",
    currencyCode: "971",
    currencyName: "AFGHANI",
  },
  {
    name: "ALAND ISLANDS",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "ALBANIA",
    currencyCode: "008",
    currencyName: "LEK",
  },
  {
    name: "ALGERIA",
    currencyCode: "012",
    currencyName: "ALGERIAN DINAR",
  },
  {
    name: "AMERICAN SAMOA",
    currencyCode: "840",
    currencyName: "US DOLLAR",
  },
  {
    name: "ANDORRA",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "ANGOLA",
    currencyCode: "973",
    currencyName: "ANGOLAN KWANZA",
  },
  {
    name: "ANGUILLA",
    currencyCode: "951",
    currencyName: "EAST CARRIBEAN DOLLAR",
  },
  {
    name: "ANTARCTICA",
    currencyCode: "578",
    currencyName: "NORWEGIAN KRONE",
  },
  {
    name: "ANTIGUA AND BARBUDA",
    currencyCode: "951",
    currencyName: "EAST CARRIBEAN DOLLAR",
  },
  {
    name: "ARGENTINA",
    currencyCode: "032",
    currencyName: "ARGENTINE PESO",
  },
  {
    name: "ARMENIA",
    currencyCode: "051",
    currencyName: "ARMENIAN DRAM",
  },
  {
    name: "ARUBA",
    currencyCode: "533",
    currencyName: "ARUBAN GUILDER",
  },
  {
    name: "AUSTRALIA",
    currencyCode: "036",
    currencyName: "AUSTRALIAN DOLLAR",
  },
  {
    name: "AUSTRIA",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "AZERBAIJAN",
    currencyCode: "944",
    currencyName: "AZERBAIJANIAN MANAT",
  },
  {
    name: "BAHAMAS",
    currencyCode: "044",
    currencyName: "BAHAMIAN DOLLAR",
  },
  {
    name: "BAHRAIN",
    currencyCode: "048",
    currencyName: "BAHRAINI DINAR",
  },
  {
    name: "BANGLADESH",
    currencyCode: "050",
    currencyName: "TAKA",
  },
  {
    name: "BARBADOS",
    currencyCode: "052",
    currencyName: "BARBADOS DOLLAR",
  },
  {
    name: "BELARUS",
    currencyCode: "933",
    currencyName: "BELARUSIAN RUBLE",
  },
  {
    name: "BELGIUM",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "BELIZE",
    currencyCode: "084",
    currencyName: "BELIZE DOLLAR",
  },
  {
    name: "BENIN",
    currencyCode: "952",
    currencyName: "CFA FRANC BCEAO",
  },
  {
    name: "BERMUDA",
    currencyCode: "060",
    currencyName: "BERMUDIAN DOLLAR",
  },
  {
    name: "BHUTAN",
    currencyCode: "064",
    currencyName: "BHUTANESE NGULTRUM",
  },
  {
    name: "BHUTAN",
    currencyCode: "356",
    currencyName: "INDIAN RUPEE",
  },
  {
    name: "BOLIVIA",
    currencyCode: "068",
    currencyName: "BOLIVIANO",
  },
  {
    name: "BONAIRE, SINT EUSTATIUS AND SABA",
    currencyCode: "840",
    currencyName: "US DOLLAR",
  },
  {
    name: "BOSNIA and HERZEGOVINA",
    currencyCode: "977",
    currencyName: "CONVERTIBLE MARK",
  },
  {
    name: "BOTSWANA",
    currencyCode: "072",
    currencyName: "PULA",
  },
  {
    name: "BOUVET ISLAND",
    currencyCode: "578",
    currencyName: "NORWEGIAN KRONE",
  },
  {
    name: "BRAZIL",
    currencyCode: "986",
    currencyName: "BRAZILIAN REAL",
  },
  {
    name: "BRAZIL",
    currencyCode: "996",
    currencyName: "SPANISH PESETA",
  },
  {
    name: "BRITISH INDIAN OCEAN TERRITORY",
    currencyCode: "840",
    currencyName: "US DOLLAR",
  },
  {
    name: "BRUNEI DARUSSALAM",
    currencyCode: "096",
    currencyName: "BRUNEI DOLLAR",
  },
  {
    name: "BULGARIA",
    currencyCode: "975",
    currencyName: "BULGARIAN LEV",
  },
  {
    name: "BURKINA FASO",
    currencyCode: "952",
    currencyName: "CFA FRANC BCEAO",
  },
  {
    name: "BURUNDI",
    currencyCode: "108",
    currencyName: "BURUNDI FRANC",
  },
  {
    name: "CAMBODIA",
    currencyCode: "116",
    currencyName: "RIEL",
  },
  {
    name: "CAMEROON",
    currencyCode: "950",
    currencyName: "CFA FRANC BEAC",
  },
  {
    name: "CANADA",
    currencyCode: "124",
    currencyName: "CANADIAN DOLLAR",
  },
  {
    name: "CAPE VERDE",
    currencyCode: "132",
    currencyName: "CAPE VERDE ESCUDO",
  },
  {
    name: "CAYMAN ISLANDS",
    currencyCode: "136",
    currencyName: "CAYMAN ISLANDS DOLLAR",
  },
  {
    name: "CENTRAL AFRICAN REPUBLIC",
    currencyCode: "950",
    currencyName: "CFA FRANC BEAC",
  },
  {
    name: "CHAD",
    currencyCode: "950",
    currencyName: "CFA FRANC BEAC",
  },
  {
    name: "CHILE",
    currencyCode: "152",
    currencyName: "CHILEAN PESO",
  },
  {
    name: "CHINA",
    currencyCode: "156",
    currencyName: "CHINESE YUAN RENMINBI",
  },
  {
    name: "CHINA",
    currencyCode: "158",
    currencyName: "CHINESE PEOPLE'S BANK",
  },
  {
    name: "CHRISTMAS ISLAND",
    currencyCode: "036",
    currencyName: "AUSTRALIAN DOLLAR",
  },
  {
    name: "COCOS (KEELING) ISLANDS",
    currencyCode: "036",
    currencyName: "AUSTRALIAN DOLLAR",
  },
  {
    name: "COLOMBIA",
    currencyCode: "170",
    currencyName: "COLOMBIAN PESO",
  },
  {
    name: "COMOROS",
    currencyCode: "174",
    currencyName: "COMORO FRANC",
  },
  {
    name: "CONGO",
    currencyCode: "950",
    currencyName: "CFA FRANC BEAC",
  },
  {
    name: "COOK ISLANDS",
    currencyCode: "554",
    currencyName: "NEW ZEALAND DOLLAR",
  },
  {
    name: "COSTA RICA",
    currencyCode: "188",
    currencyName: "COSTA RICAN COLON",
  },
  {
    name: "COTE D’IVOIRE (IVORY COAST)",
    currencyCode: "952",
    currencyName: "CFA FRANC BCEAO",
  },
  {
    name: "CROATIA",
    currencyCode: "191",
    currencyName: "CROATIAN KUNA",
  },
  {
    name: "CURACAO",
    currencyCode: "532",
    currencyName: "NETHERLANDS ANTILLEAN",
  },
  {
    name: "CYPRUS",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "CZECH REPUBLIC",
    currencyCode: "203",
    currencyName: "CZECH KORUNA",
  },
  {
    name: "DEMOCRATIC REPUBLIC OF THE CONGO",
    currencyCode: "976",
    currencyName: "CONGOLESE",
  },
  {
    name: "DENMARK",
    currencyCode: "208",
    currencyName: "DANISH KRONE",
  },
  {
    name: "DJIBOUTI",
    currencyCode: "262",
    currencyName: "DJIBOUTI FRANC",
  },
  {
    name: "DOMINICA",
    currencyCode: "951",
    currencyName: "EAST CARRIBEAN DOLLAR",
  },
  {
    name: "DOMINICAN REPUBLIC",
    currencyCode: "214",
    currencyName: "DOMINICAN PESO",
  },
  {
    name: "EGYPT",
    currencyCode: "818",
    currencyName: "EGYPTIAN POUND",
  },
  {
    name: "EL SALVADOR",
    currencyCode: "222",
    currencyName: "EL SALVADOR COLON",
  },
  {
    name: "ECUADOR",
    currencyCode: "840",
    currencyName: "US DOLLAR",
  },
  {
    name: "EQUATORIAL GUINEA",
    currencyCode: "950",
    currencyName: "CFA FRANC BEAC",
  },
  {
    name: "ERITREA",
    currencyCode: "230",
    currencyName: "ETHIOPIAN BIRR",
  },
  {
    name: "ERITREA",
    currencyCode: "232",
    currencyName: "ERITREAN NAKFA",
  },
  {
    name: "ESTONIA",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "ETHIOPIA",
    currencyCode: "230",
    currencyName: "ETHIOPIAN BIRR",
  },
  {
    name: "FALKLAND ISLANDS (MALVINAS)",
    currencyCode: "238",
    currencyName: "FALKLAND ISLANDS POUND",
  },
  {
    name: "FEDERATED STATES OF MICRONESIA",
    currencyCode: "840",
    currencyName: "US",
  },
  {
    name: "FIJI",
    currencyCode: "242",
    currencyName: "FIJI DOLLAR",
  },
  {
    name: "FINLAND",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "FRANCE",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "FRANCE, METROPOLITAN",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "FRENCH GUIANA",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "FRENCH POLYNESIA",
    currencyCode: "953",
    currencyName: "CFP FRANC",
  },
  {
    name: "GABON",
    currencyCode: "950",
    currencyName: "CFA FRANC BEAC",
  },
  {
    name: "GAMBIA",
    currencyCode: "270",
    currencyName: "DALASI",
  },
  {
    name: "GEORGIA",
    currencyCode: "981",
    currencyName: "LARI",
  },
  {
    name: "GERMANY",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "GHANA",
    currencyCode: "936",
    currencyName: "CEDI",
  },
  {
    name: "GIBRALTAR",
    currencyCode: "292",
    currencyName: "GIBRALTAR POUND",
  },
  {
    name: "GREECE",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "GREENLAND",
    currencyCode: "208",
    currencyName: "DANISH KRONE",
  },
  {
    name: "GRENADA",
    currencyCode: "951",
    currencyName: "EAST CARRIBEAN DOLLAR",
  },
  {
    name: "GUADELOUPE",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "GUAM",
    currencyCode: "840",
    currencyName: "US DOLLAR",
  },
  {
    name: "GUATEMALA",
    currencyCode: "320",
    currencyName: "QUETZAL",
  },
  {
    name: "GUINEA-BISSAU",
    currencyCode: "952",
    currencyName: "CFA FRANC BCEAO",
  },
  {
    name: "GUINEA",
    currencyCode: "324",
    currencyName: "GUINEA FRANC",
  },
  {
    name: "GUYANA",
    currencyCode: "328",
    currencyName: "GUYANA DOLLAR",
  },
  {
    name: "HAITI",
    currencyCode: "332",
    currencyName: "GOURDE",
  },
  {
    name: "HEARD and MCDONALD ISLANDS",
    currencyCode: "036",
    currencyName: "AUSTRALIAN DOLLAR",
  },
  {
    name: "HOLY SEE (VATICAN CITY STATE)",
    currencyCode: "",
    currencyName: "978",
  },
  {
    name: "HONDURUS",
    currencyCode: "340",
    currencyName: "LEMPIRA",
  },
  {
    name: "HONG KONG",
    currencyCode: "344",
    currencyName: "HONG KONG DOLLAR",
  },
  {
    name: "HUNGARY",
    currencyCode: "348",
    currencyName: "FORINT",
  },
  {
    name: "ICELAND",
    currencyCode: "352",
    currencyName: "ICELANDIC KRONA",
  },
  {
    name: "INDIA",
    currencyCode: "356",
    currencyName: "INDIAN RUPEE",
  },
  {
    name: "INDONESIA",
    currencyCode: "360",
    currencyName: "RUPIAH",
  },
  {
    name: "IRAQ",
    currencyCode: "368",
    currencyName: "IRAQI DINAR",
  },
  {
    name: "ISRAEL",
    currencyCode: "376",
    currencyName: "NEW ISRAELI SHEKEL",
  },
  {
    name: "IRELAND",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "ISLE OF MAN",
    currencyCode: "826",
    currencyName: "POUND STERLING",
  },
  {
    name: "ITALY",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "JAMAICA",
    currencyCode: "388",
    currencyName: "JAMAICAN DOLLAR",
  },
  {
    name: "JAPAN",
    currencyCode: "392",
    currencyName: "YEN",
  },
  {
    name: "JERSEY",
    currencyCode: "826",
    currencyName: "POUND STERLING",
  },
  {
    name: "JORDAN",
    currencyCode: "400",
    currencyName: "JORDANIAN DINAR",
  },
  {
    name: "KAZAKHSTAN",
    currencyCode: "398",
    currencyName: "TENGE",
  },
  {
    name: "KENYA",
    currencyCode: "404",
    currencyName: "KENYAN SHILLING",
  },
  {
    name: "KIRIBATI",
    currencyCode: "036",
    currencyName: "AUSTRALIAN DOLLAR",
  },
  {
    name: "KOREA, REPUBLIC OF",
    currencyCode: "410",
    currencyName: "WON",
  },
  {
    name: "KUWAIT",
    currencyCode: "414",
    currencyName: "KUWAITI DINAR",
  },
  {
    name: "KYRGYZSTAN",
    currencyCode: "417",
    currencyName: "SOM",
  },
  {
    name: "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
    currencyCode: "418",
    currencyName: "KIP",
  },
  {
    name: "LATVIA",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "LEBANON",
    currencyCode: "422",
    currencyName: "LEBANESE POUND",
  },
  {
    name: "LESOTHO",
    currencyCode: "426",
    currencyName: "LOTI",
  },
  {
    name: "LESOTHO",
    currencyCode: "710",
    currencyName: "RAND",
  },
  {
    name: "LIBERIA",
    currencyCode: "430",
    currencyName: "LIBERIAN DOLLAR",
  },
  {
    name: "LIBYAN ARAB JAMAHIRIYA",
    currencyCode: "434",
    currencyName: "LIBYAN DINAR",
  },
  {
    name: "LIECHTENSTEIN",
    currencyCode: "756",
    currencyName: "SWISS FRANC",
  },
  {
    name: "LITHUANIA",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "LUXEMBOURG",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "MACAO",
    currencyCode: "446",
    currencyName: "PATACA",
  },
  {
    name: "MACEDONIA",
    currencyCode: "807",
    currencyName: "DENAR",
  },
  {
    name: "MADAGASCAR",
    currencyCode: "969",
    currencyName: "MALAGASY ARIARY",
  },
  {
    name: "MALAWI",
    currencyCode: "454",
    currencyName: "MALAWI KWACHA",
  },
  {
    name: "MALAYSIA",
    currencyCode: "458",
    currencyName: "MALAYSIAN RINGGIT",
  },
  {
    name: "MALDIVES",
    currencyCode: "462",
    currencyName: "RUFIYAA",
  },
  {
    name: "MALI",
    currencyCode: "952",
    currencyName: "CFA FRANC BCEAO",
  },
  {
    name: "MALTA",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "MARSHALL ISLANDS",
    currencyCode: "840",
    currencyName: "US DOLLAR",
  },
  {
    name: "MARTINIQUE",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "MAURITANIA",
    currencyCode: "929",
    currencyName: "OUGUIYA",
  },
  {
    name: "MAURITIUS",
    currencyCode: "480",
    currencyName: "MAURITIUS RUPEE",
  },
  {
    name: "MAYOTTE",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "MEXICO",
    currencyCode: "484",
    currencyName: "MEXICAN PESO",
  },
  {
    name: "MOLDOVA, REPUBLIC OF",
    currencyCode: "498",
    currencyName: "MOLDOVAN LEU",
  },
  {
    name: "MONACO",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "MONGOLIA",
    currencyCode: "496",
    currencyName: "TUGRIK",
  },
  {
    name: "MONTENEGRO, REPUBLIC OF",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "MONTSERRAT",
    currencyCode: "951",
    currencyName: "EAST CARRIBEAN DOLLAR",
  },
  {
    name: "MOROCCO",
    currencyCode: "002",
    currencyName: "MOROCCAN DIRHAM",
  },
  {
    name: "MOZAMBIQUE",
    currencyCode: "943",
    currencyName: "MOZAMBIQUE METICAL",
  },
  {
    name: "MYANMAR",
    currencyCode: "104",
    currencyName: "MYANMAR KYAT",
  },
  {
    name: "NAMIBIA",
    currencyCode: "516",
    currencyName: "NAMIBIAN DOLLAR",
  },
  {
    name: "NAURU",
    currencyCode: "036",
    currencyName: "AUSTRALIAN DOLLAR",
  },
  {
    name: "NEPAL",
    currencyCode: "524",
    currencyName: "NEPALESE RUPEE",
  },
  {
    name: "NETHERLANDS",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "NETHERLANDS ANTILLES",
    currencyCode: "532",
    currencyName: "NETHLANDES ANTILLIAN",
  },
  {
    name: "NEW CALEDONIA",
    currencyCode: "953",
    currencyName: "CFP FRANC",
  },
  {
    name: "NEW ZEALAND",
    currencyCode: "554",
    currencyName: "NEW ZEALAND DOLLAR",
  },
  {
    name: "NICARAGUA",
    currencyCode: "558",
    currencyName: "CORDOBA ORO",
  },
  {
    name: "NIGER",
    currencyCode: "952",
    currencyName: "CFA FRANC BCEAO",
  },
  {
    name: "NIGERIA",
    currencyCode: "566",
    currencyName: "NAIRA",
  },
  {
    name: "NIUE",
    currencyCode: "554",
    currencyName: "NEW ZEALAND DOLLAR",
  },
  {
    name: "NORFOLK ISLAND",
    currencyCode: "036",
    currencyName: "AUSTRALIAN DOLLAR",
  },
  {
    name: "NORTHERN MARIANA ISLANDS",
    currencyCode: "840",
    currencyName: "US DOLLAR",
  },
  {
    name: "NORWAY",
    currencyCode: "578",
    currencyName: "NORWEGIAN KRONE",
  },
  {
    name: "OMAN",
    currencyCode: "512",
    currencyName: "RIAL OMANI",
  },
  {
    name: "PAKISTAN",
    currencyCode: "586",
    currencyName: "PAKISTAN RUPEE",
  },
  {
    name: "PALAU",
    currencyCode: "840",
    currencyName: "US DOLLAR",
  },
  {
    name: "PANAMA",
    currencyCode: "590",
    currencyName: "BALBOA",
  },
  {
    name: "PAPUA NEW GUINEA",
    currencyCode: "598",
    currencyName: "KINA",
  },
  {
    name: "PARAGUAY",
    currencyCode: "600",
    currencyName: "GUARANI",
  },
  {
    name: "PERU",
    currencyCode: "604",
    currencyName: "NUEVO SOL",
  },
  {
    name: "PHILIPPINES",
    currencyCode: "608",
    currencyName: "PHILIPPINE PESO",
  },
  {
    name: "PITCAIRN",
    currencyCode: "554",
    currencyName: "NEW ZEALAND DOLLAR",
  },
  {
    name: "POLAND",
    currencyCode: "985",
    currencyName: "ZLOTY",
  },
  {
    name: "PORTUGAL",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "PUERTO RICO",
    currencyCode: "840",
    currencyName: "US DOLLAR",
  },
  {
    name: "QATAR",
    currencyCode: "634",
    currencyName: "QATARI RIAL",
  },
  {
    name: "REUNION",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "ROMANIA",
    currencyCode: "946",
    currencyName: "ROMANIAN LEU",
  },
  {
    name: "RUSSIAN FEDERATION",
    currencyCode: "643",
    currencyName: "RUSSIAN RUBLE",
  },
  {
    name: "RWANDA",
    currencyCode: "646",
    currencyName: "RWANDA FRANC",
  },
  {
    name: "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA",
    currencyCode: "654",
    currencyName: "ST. HELENA",
  },
  {
    name: "SAMOA",
    currencyCode: "882",
    currencyName: "TALA",
  },
  {
    name: "SAN MARINO",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "SAO TOME AND PRINCIPE",
    currencyCode: "930",
    currencyName: "DOBRA",
  },
  {
    name: "SAUDI ARABIA",
    currencyCode: "682",
    currencyName: "SAUDI RIYAL",
  },
  {
    name: "SENEGAL",
    currencyCode: "952",
    currencyName: "CFA FRANC BCEAO",
  },
  {
    name: "SERBIA",
    currencyCode: "941",
    currencyName: "SERBIAN DINAR",
  },
  {
    name: "SEYCHELLES",
    currencyCode: "690",
    currencyName: "SEYCHELLES RUPEE",
  },
  {
    name: "SIERRA LEONE",
    currencyCode: "694",
    currencyName: "LEONE",
  },
  {
    name: "SINGAPORE",
    currencyCode: "702",
    currencyName: "SINGAPORE DOLLAR",
  },
  {
    name: "SINT MAARTEN (DUTCH PART)",
    currencyCode: "532",
    currencyName: "NETHERLANDS ANTILLES",
  },
  {
    name: "SLOVAKIA",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "SLOVENIA",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "SOLOMON ISLANDS",
    currencyCode: "090",
    currencyName: "SOLOMON ISLANDS DOLLAR",
  },
  {
    name: "SOMALIA",
    currencyCode: "706",
    currencyName: "SOMALI SHILLING",
  },
  {
    name: "SOUTH AFRICA",
    currencyCode: "710",
    currencyName: "RAND",
  },
  {
    name: "SOUTH SUDAN",
    currencyCode: "728",
    currencyName: "SOUTH SUDANESE POUND",
  },
  {
    name: "SPAIN",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "SRI LANKA",
    currencyCode: "144",
    currencyName: "SRI LANKA RUPEE",
  },
  {
    name: "ST. KITTS-NEVIS",
    currencyCode: "951",
    currencyName: "EAST CARRIBEAN DOLLAR",
  },
  {
    name: "ST. LUCIA",
    currencyCode: "951",
    currencyName: "EAST CARRIBEAN DOLLAR",
  },
  {
    name: "ST. PIERRE AND MIQUELON",
    currencyCode: "978",
    currencyName: "EURO",
  },
  {
    name: "ST. VINCENT AND THE GRENADINES",
    currencyCode: "951",
    currencyName: "EAST CARRIBEAN",
  },
  {
    name: "SURINAME",
    currencyCode: "968",
    currencyName: "SURINAME DOLLAR",
  },
  {
    name: "SVALBARD AND JAN MAYEN",
    currencyCode: "578",
    currencyName: "NORWEGIAN KRONE",
  },
  {
    name: "SWITZERLAND",
    currencyCode: "756",
    currencyName: "SWISS FRANC",
  },
  {
    name: "SWAZILAND",
    currencyCode: "748",
    currencyName: "LILANGENI",
  },
  {
    name: "SWEDEN",
    currencyCode: "752",
    currencyName: "SWEDISH KRONA",
  },
  {
    name: "TAIWAN",
    currencyCode: "901",
    currencyName: "NEW TAIWAN DOLLAR",
  },
  {
    name: "TAJIKISTAN",
    currencyCode: "972",
    currencyName: "SOMONI",
  },
  {
    name: "TANZANIA, UNITED REPUBLIC OF",
    currencyCode: "834",
    currencyName: "TANZANIAN",
  },
  {
    name: "THAILAND",
    currencyCode: "764",
    currencyName: "BAHT",
  },
  {
    name: "TIMOR-LESTE",
    currencyCode: "840",
    currencyName: "US DOLLAR",
  },
  {
    name: "TOGO",
    currencyCode: "952",
    currencyName: "CFA FRANC BCEAO",
  },
  {
    name: "TOKELAU",
    currencyCode: "554",
    currencyName: "NEW ZEALAND DOLLAR",
  },
  {
    name: "TONGA",
    currencyCode: "776",
    currencyName: "PA'ANGA",
  },
  {
    name: "TRINIDAD AND TOBAGO",
    currencyCode: "780",
    currencyName: "TRINIDAD AND TOBAGO",
  },
  {
    name: "TUNISIA",
    currencyCode: "788",
    currencyName: "TUNISIAN DINAR",
  },
  {
    name: "TURKEY",
    currencyCode: "949",
    currencyName: "TURKISH LIRA",
  },
  {
    name: "TURKMENISTAN",
    currencyCode: "934",
    currencyName: "MANAT",
  },
  {
    name: "TURKS and CAICOS ISLANDS",
    currencyCode: "840",
    currencyName: "US DOLLAR",
  },
  {
    name: "TUVALU",
    currencyCode: "036",
    currencyName: "AUSTRALIAN DOLLAR",
  },
  {
    name: "UGANDA",
    currencyCode: "800",
    currencyName: "UGANDAN SHILLING",
  },
  {
    name: "UKRAINE",
    currencyCode: "980",
    currencyName: "UKRAINIAN HRYVNIA",
  },
  {
    name: "UNITED ARAB EMIRATES",
    currencyCode: "784",
    currencyName: "U.A.E. DIRHAM",
  },
  {
    name: "UNITED KINGDOM",
    currencyCode: "826",
    currencyName: "POUND STERLING",
  },
  {
    name: "UNITED STATES",
    currencyCode: "840",
    currencyName: "US DOLLAR",
  },
  {
    name: "URUGUAY",
    currencyCode: "858",
    currencyName: "PESO URUGUAYO",
  },
  {
    name: "UZBEKISTAN",
    currencyCode: "860",
    currencyName: "UZBEKISTAN SUM",
  },
  {
    name: "VANUATU",
    currencyCode: "548",
    currencyName: "VATU",
  },
  {
    name: "VENEZUELA",
    currencyCode: "928",
    currencyName: "BOLIVAR SOBERANO",
  },
  {
    name: "VIETNAM",
    currencyCode: "704",
    currencyName: "DONG",
  },
  {
    name: "BRITISH VIRGIN ISLANDS",
    currencyCode: "840",
    currencyName: "US DOLLAR",
  },
  {
    name: "U.S. VIRGIN ISLANDS",
    currencyCode: "840",
    currencyName: "US DOLLAR",
  },
  {
    name: "WALLIS AND FUTUNA ISLANDS",
    currencyCode: "953",
    currencyName: "CFP FRANC",
  },
  {
    name: "WESTERN SAHARA",
    currencyCode: "504",
    currencyName: "MOROCCAN DIRHAM",
  },
  {
    name: "YEMEN",
    currencyCode: "886",
    currencyName: "YEMENI RIAL",
  },
  {
    name: "ZAMBIA",
    currencyCode: "967",
    currencyName: "ZAMBIAN KWACHA",
  },
  {
    name: "ZIMBABWE",
    currencyCode: "716",
    currencyName: "ZIMBABWE DOLLAR",
  },
  {
    name: "CUBA",
    currencyCode: "192",
    currencyName: "CUBAN PESO",
  },
  {
    name: "ECUADOR",
    currencyCode: "218",
    currencyName: "SUCRE",
  },
  {
    name: "IRAN",
    currencyCode: "364",
    currencyName: "IRANIAN RIAL",
  },
  {
    name: "LATVIA",
    currencyCode: "428",
    currencyName: "LATVIAN LATS",
  },
  {
    name: "LITHUANIA",
    currencyCode: "440",
    currencyName: "LITHUANIAN LITAS",
  },
  {
    name: "GUINEA-BISSAU",
    currencyCode: "624",
    currencyName: "GUINEA-BISSAU PESO",
  },
  {
    name: "SYRIA",
    currencyCode: "760",
    currencyName: "SYRIAN POUND",
  },
  {
    name: "TONGA",
    currencyCode: "776",
    currencyName: "PA’ANGA",
  },
];
